base:
  random_seed: 0
  model_image_size: 512
  # Loss needs to be here since both train and evaluate need it
  loss_function: categorical_crossentropy # Options: binary_crossentropy, iou_loss, dice_loss
  image_channels: 1
  output_classes: 2
data_split:
  test_split: 0.2
  data_dir: data/all_data/
  train_data_dir: data/train/
  test_data_dir: data/test/
train:
  train_data_dir: data/train/
  model_save_dir: models/
  batch_size: 1
  epochs: 5
  conv_activation_function: relu # Options: relu, sigmoid
  final_activation_function: softmax # Options: softmax (for multi-class), sigmoid (for binary)
  learning_rate: 0.001
  norm_upper_bound: 7
  norm_lower_bound: -1
  validation_split: 0.2
evaluate:
  model_path: models/dna-damage-model.keras
  test_data_dir: data/test/



